spring.application.name=AiMeet
spring.datasource.url = jdbc:postgresql://localhost:5432/AiMeeting
spring.datasource.username = postgres
spring.datasource.password=abcd
string.datasource.drive-class-name= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update
server.port = 8080